---
- name: Restart gogs
  systemd:
    state: restarted
    enabled: yes
    daemon_reload: yes
    name: gogs
  listen: h_restart-gogs

- name: Restart nginx
  systemd:
    state: restarted
    enabled: yes
    daemon_reload: yes
    name: nginx
  listen: h_restart-nginx